In [1]:
# Task 3
!jupyter nbextension enable --py widgetsnbextension
import codecs
import tensorflow as tf
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification
from ipywidgets import FloatProgress
from transformers import pipeline

Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK


2023-01-25 16:02:25.713097: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-25 16:02:26.290551: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-01-25 16:02:26.290590: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-01-25 16:02:28.495199: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-01-2

In [2]:
classifier = pipeline('sentiment-analysis')

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
2023-01-25 16:02:47.101644: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2023-01-25 16:02:47.102380: W tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
2023-01-25 16:02:47.102469: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (kali): /proc/driver/nvidia/version does not exist
2023-01-25 16:02:47.103911: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Netwo

In [9]:
nlp_qusetion_answering = pipeline('question-answering')
nlp_qusetion_answering(context='Definetly', question='Am I a good student?')

No model was supplied, defaulted to distilbert-base-cased-distilled-squad and revision 626af31 (https://huggingface.co/distilbert-base-cased-distilled-squad).
Using a pipeline without specifying a model name and revision in production is not recommended.


Downloading:   0%|          | 0.00/473 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/261M [00:00<?, ?B/s]

Some layers from the model checkpoint at distilbert-base-cased-distilled-squad were not used when initializing TFDistilBertForQuestionAnswering: ['dropout_19']
- This IS expected if you are initializing TFDistilBertForQuestionAnswering from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertForQuestionAnswering from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some layers of TFDistilBertForQuestionAnswering were not initialized from the model checkpoint at distilbert-base-cased-distilled-squad and are newly initialized: ['dropout_39']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Downloading:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/213k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/436k [00:00<?, ?B/s]

{'score': 0.8583741784095764, 'start': 0, 'end': 9, 'answer': 'Definetly'}

In [5]:
text_one = 'Vladislav Stoliarchuk'
classifier(text_one)

[{'label': 'POSITIVE', 'score': 0.9955266118049622}]

In [6]:
text_two = 'Ukraine)'
classifier(text_two)

[{'label': 'POSITIVE', 'score': 0.9590654373168945}]

In [7]:
text_three = 'FB-21mp'
classifier(text_three)

[{'label': 'NEGATIVE', 'score': 0.9895161390304565}]

In [10]:
text_four = 'IPT'
classifier(text_four)

[{'label': 'NEGATIVE', 'score': 0.5971269011497498}]

In [11]:
text_five = 'Ukraine will easy beat russia'
classifier(text_five)

[{'label': 'POSITIVE', 'score': 0.9974727034568787}]

In [3]:
model_name = "distilbert-base-uncased-finetuned-sst-2-english"
model = TFAutoModelForSequenceClassification.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

Some layers from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english were not used when initializing TFDistilBertForSequenceClassification: ['dropout_19']
- This IS expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some layers of TFDistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english and are newly initialized: ['dropout_39']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [12]:
Input = tokenizer([text_one, text_two])
Input

{'input_ids': [[101, 19163, 19834, 2358, 10893, 2906, 26516, 102], [101, 5924, 1007, 102]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1]]}

In [13]:
Input_with_padding = tokenizer([text_one, text_two], padding = True, truncation = True, max_length = 256, return_tensors="tf")
Input_with_padding

{'input_ids': <tf.Tensor: shape=(2, 8), dtype=int32, numpy=
array([[  101, 19163, 19834,  2358, 10893,  2906, 26516,   102],
       [  101,  5924,  1007,   102,     0,     0,     0,     0]],
      dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 8), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 0, 0, 0, 0]], dtype=int32)>}

In [14]:
Output = model(Input_with_padding)
Output

TFSequenceClassifierOutput(loss=None, logits=<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-2.654481 ,  2.750637 ],
       [-1.5043954,  1.6495923]], dtype=float32)>, hidden_states=None, attentions=None)

In [15]:
prediction = tf.nn.softmax(Output[0], axis=-1)
prediction

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.00447342, 0.9955266 ],
       [0.04093444, 0.95906556]], dtype=float32)>

In [16]:
Input = tokenizer([text_one, text_two, text_three])
Input

{'input_ids': [[101, 19163, 19834, 2358, 10893, 2906, 26516, 102], [101, 5924, 1007, 102], [101, 1042, 2497, 1011, 2538, 8737, 102]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1]]}

In [17]:
Input_with_padding = tokenizer([text_one, text_two, text_three], padding = True, truncation = True, max_length = 256, return_tensors="tf")
Input_with_padding

{'input_ids': <tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[  101, 19163, 19834,  2358, 10893,  2906, 26516,   102],
       [  101,  5924,  1007,   102,     0,     0,     0,     0],
       [  101,  1042,  2497,  1011,  2538,  8737,   102,     0]],
      dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 0]], dtype=int32)>}

In [18]:
Output = model(Input_with_padding)
Output

TFSequenceClassifierOutput(loss=None, logits=<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-2.654481 ,  2.750637 ],
       [-1.5043954,  1.6495922],
       [ 2.4833713, -2.0640035]], dtype=float32)>, hidden_states=None, attentions=None)

In [19]:
prediction = tf.nn.softmax(Outputs[0], axis=-1)
prediction

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.00447342, 0.9955266 ],
       [0.04093445, 0.95906556],
       [0.98951614, 0.01048391]], dtype=float32)>

In [20]:
Input = tokenizer([text_one, text_two, text_three, text_four])
Input

{'input_ids': [[101, 19163, 19834, 2358, 10893, 2906, 26516, 102], [101, 5924, 1007, 102], [101, 1042, 2497, 1011, 2538, 8737, 102], [101, 12997, 2102, 102]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1]]}

In [21]:
Input_with_padding = tokenizer([text_one, text_two, text_three, text_four], padding = True, truncation = True, max_length = 256, return_tensors="tf")
Input_with_padding

{'input_ids': <tf.Tensor: shape=(4, 8), dtype=int32, numpy=
array([[  101, 19163, 19834,  2358, 10893,  2906, 26516,   102],
       [  101,  5924,  1007,   102,     0,     0,     0,     0],
       [  101,  1042,  2497,  1011,  2538,  8737,   102,     0],
       [  101, 12997,  2102,   102,     0,     0,     0,     0]],
      dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(4, 8), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 0, 0, 0, 0]], dtype=int32)>}

In [22]:
Output = model(Input_with_padding)
Output

TFSequenceClassifierOutput(loss=None, logits=<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[-2.6544807 ,  2.750637  ],
       [-1.5043954 ,  1.6495923 ],
       [ 2.4833713 , -2.0640035 ],
       [ 0.3297074 , -0.06381101]], dtype=float32)>, hidden_states=None, attentions=None)

In [23]:
prediction = tf.nn.softmax(Output[0], axis=-1)
prediction

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[0.00447342, 0.9955266 ],
       [0.04093444, 0.95906556],
       [0.98951614, 0.01048391],
       [0.5971294 , 0.4028706 ]], dtype=float32)>

In [24]:
Input = tokenizer([text_one, text_two, text_three, text_four, text_five])
Input

{'input_ids': [[101, 19163, 19834, 2358, 10893, 2906, 26516, 102], [101, 5924, 1007, 102], [101, 1042, 2497, 1011, 2538, 8737, 102], [101, 12997, 2102, 102], [101, 5924, 2097, 3733, 3786, 3607, 102]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1]]}

In [25]:
Input_with_padding = tokenizer([text_one, text_two, text_three, text_four, text_five], padding = True, truncation = True, max_length = 256, return_tensors="tf")
Input_with_padding

{'input_ids': <tf.Tensor: shape=(5, 8), dtype=int32, numpy=
array([[  101, 19163, 19834,  2358, 10893,  2906, 26516,   102],
       [  101,  5924,  1007,   102,     0,     0,     0,     0],
       [  101,  1042,  2497,  1011,  2538,  8737,   102,     0],
       [  101, 12997,  2102,   102,     0,     0,     0,     0],
       [  101,  5924,  2097,  3733,  3786,  3607,   102,     0]],
      dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(5, 8), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 0]], dtype=int32)>}

In [26]:
Output = model(Input_with_padding)
Output

TFSequenceClassifierOutput(loss=None, logits=<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[-2.6544807 ,  2.750637  ],
       [-1.5043954 ,  1.6495923 ],
       [ 2.4833713 , -2.0640035 ],
       [ 0.3297074 , -0.06381101],
       [-2.9337354 ,  3.0443406 ]], dtype=float32)>, hidden_states=None, attentions=None)

In [27]:
prediction = tf.nn.softmax(Output[0], axis=-1)
prediction

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[0.00447342, 0.9955266 ],
       [0.04093444, 0.95906556],
       [0.98951614, 0.01048391],
       [0.5971294 , 0.4028706 ],
       [0.00252729, 0.9974727 ]], dtype=float32)>